### ISSUE TITLE
Div won't disappear on click

### ISSUE THREAD

**Issue by ksjdragon** [ksjdragon/atoms#1]
"this.parentNode.style.*** = 'something'" doesn't seem to work when coming from a child node.

**Comment by yamanq** [comment]
elaboration?

**Comment by ksjdragon** [comment]
It doesn't work, I can't say much more than that. Nothing happens. When I run that line of code

**Comment by ksjdragon** [comment]
fixed c8d12738f389676b322f749e8dc211e7ea2170e7
