### ISSUE TITLE
"Display Theme" rather than "Atom Theme" and "Table Theme"

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#10]

**Comment by ksjdragon** [comment]
I want the atom theme and table theme to be separate, so more customization is possible. If you want to suggest different names for them, go ahead.

**Comment by yamanq** [comment]
This leads to confusion as the table and the atom colors are different. Having Display Theme is more practical.
Example: User is browsing boiling points. User most likely wants to see chlorine in its respective boiling point, not its ionization energy.

**Comment by ksjdragon** [comment]
Ok

**Comment by ksjdragon** [comment]
I can change it.

**Comment by ksjdragon** [comment]
Didn't mean to send that in two messages.

**Comment by ksjdragon** [comment]
fixed in b595e04eceaf86869799e8745173f9c30960c42d
