### ISSUE TITLE
Local copy displays no (js?) content

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#12]
file:///home/.../index.html displays website with no (js?) content. No displayed settings (just headers) or periodic table

**Comment by ksjdragon** [comment]
This website doesn't work on local. It must run on a server. That's not a bug, it's simply because browsers don't allow local access or cookies when running from file://...

**Comment by ksjdragon** [comment]
Also, remember to clear cache to see updates sometimes

**Comment by yamanq** [comment]
works on firefox
