### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#13]
Colors not explained
Solution: 

- For black and white data (region) display a normal  legend
- For variable (boiling point) include [scale](http://i.imgur.com/qm5Dc2B.jpg) of values

**Comment by ksjdragon** [comment]
I planned to do that, i just was going to make eyes first.

**Comment by yamanq** [comment]
Working on this

**Comment by yamanq** [comment]
205b4bf6485f776a7e7a076ebaf41ab27e322633
