### ISSUE TITLE
Help text should be custom div

### ISSUE THREAD

**Issue by ksjdragon** [ksjdragon/atoms#14]

**Comment by yamanq** [comment]
This is what is happening at the moment.

**Comment by ksjdragon** [comment]
I meant like a styled div that would appea after .7 seconds or something, not just title

**Comment by ksjdragon** [comment]
I couldn't change issue on mobile, or at least I don't know how

**Comment by yamanq** [comment]
Will do

**Comment by yamanq** [comment]
I found complications sorry can't do

**Comment by ksjdragon** [comment]
Ok, i'll do it

**Comment by ksjdragon** [comment]
fixed c8d12738f389676b322f749e8dc211e7ea2170e7
