### ISSUE TITLE
Change Electron ring gifs to electrons only

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#15]
This will allow customization of the actual ring which will not only solve #4, but also create a more informative display: when we get to bonding, we already have a way to display a stable element

**Comment by ksjdragon** [comment]
I think this is a good idea, I'll do that.

**Comment by yamanq** [comment]
in that case, I will close #4

**Comment by ksjdragon** [comment]
fixed 8263c58f1625f1458510502ca1527fe331a1438e

**Comment by yamanq** [comment]
"StableRing" series un necessary but that is a different issue
