### ISSUE TITLE
Better commenting

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#23]

**Comment by ksjdragon** [comment]
I don't really want to flood the page with comments. But if you can provide specific instances of where it would be helpful, I can adjust to that.

**Comment by yamanq** [comment]
Most of the cookies and referencing to the theme references (including getting colors) is all that's absolutely necessary

**Comment by ksjdragon** [comment]
Ok, next commit of mine is changing the organization of the js by separating it, if possible. I'll see what I can do.

**Comment by ksjdragon** [comment]
added more comments in 9115ea685455af6807df7f0bef43b828319778b9. If you need more, comment on this again.
