### ISSUE TITLE
Dark theme non-aesthetic

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#24]
When hovering over the X on the tab in dark theme, it turns red, the background is also red

**Comment by ksjdragon** [comment]
We're going to change the colors of the dark theme anyway, so suggest a color.

**Comment by yamanq** [comment]
#68893D

**Comment by yamanq** [comment]
d1661f9c23505db916ca9fb27a2316e7ca4e1921

**Comment by ksjdragon** [comment]
f2b8faacb6906398b37ca79bb0b3f79f63b628aa

**Comment by yamanq** [comment]
This makes the dark theme much too dull. I don't understand why you overwrote my commit without any reasoning.

**Comment by yamanq** [comment]
ab73a52c21f8ad99393d240cec3fc6a584583206
