### ISSUE TITLE
Disappearing Help

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#28]
Steps to reproduce:

1. Place cursor on bottom half of "?" div
2. Click
3. Help text appears then disappears

**Comment by ksjdragon** [comment]
Can't reproduce. KEep your mouse on the cursor.

**Comment by yamanq** [comment]
I sent a file to you on #dev concerning this

**Comment by yamanq** [comment]
d7404b2ff1ae1fa28267d86145414670d41a0050
