### ISSUE TITLE
electrons are too big for line, orbiting on outside of line

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#29]

**Comment by ksjdragon** [comment]
The line was not meant to be a ring for it to circle. It was simply just a design of the center part.

**Comment by yamanq** [comment]
design meaning what?

**Comment by ksjdragon** [comment]
Just look at it.

**Comment by yamanq** [comment]
Nothing changed.

**Comment by ksjdragon** [comment]
aaf9db3d539514bbb41d0a316cf73c7c95aa5c81 This is slightly changed here
