### ISSUE TITLE
Noble gasses shouldn't have rings

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#4]
This has become more clear with solving of issue #5 as even with slower electrons, it is difficult to distinguish between 7 and 8 electrons. The target audience is mainly people with at least a basic understanding of chemistry so implications of no valence electrons do not apply. Having those valence electrons adds confusion/irrelevance as they are not important to bonding.

**Comment by ksjdragon** [comment]
While the implication is not necessarily the problem, it is incredibly awkward to suddenly just drop a part of the design. I suggest making the electrons smaller, suggesting that they can't bond, and creating less of a distraction

**Comment by yamanq** [comment]
You didn't address my point very clearly. The electrons are irrelevant: part of a complete shell. 
To respond to you, It is not dropping part of the design as the design does not display complete shells, unless that is a future feature of having all electrons shown.
Making the electrons smaller does not give that implication. If that route is to be taken (modifying the electrons to give an implication) changing the color would be the best route. However, since they are gifs, good color management is not quite possible yet. To convert them out of gif format would take a decent amount of time. So the best solution is to simply remove them.
Dropping part of the design is sometimes necessary.

**Comment by ksjdragon** [comment]
The design represents the valence electrons. I do not see thenecessity of changing this, as I don't see how it is confusing. The relevency is simply representing the valence electrons, whether it is "necessary" or not. Kinda like adding descriptions and names to the info. While obviously 1s2 isn't element name, it's good to have there

**Comment by yamanq** [comment]
>  it is difficult to distinguish between 7 and 8 electrons.

**Comment by yamanq** [comment]
#15
