### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#8]
GNU GPLv3

**Comment by ksjdragon** [comment]
I'll add it in if you want.

**Comment by yamanq** [comment]
ok, because license changes require unanimous approval from all sources of code I was just checking with you. I can do this

**Comment by ksjdragon** [comment]
Or you can add it in, actually

**Comment by yamanq** [comment]
1c478092641646c5b0a5f4f700f65f082a306d51
