### ISSUE TITLE
Scrollbar not working properly

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/atoms#9]
User does not know if there is additional content as there is no scrollbar

**Comment by ksjdragon** [comment]
There will not be a need for a scrollbar at the end, as the "workspace" for the atoms will be moved through dragging and clicking.

**Comment by yamanq** [comment]
[http://i.imgur.com/9RJlp0w.png](url)
^Explanation of "Fit-all Solution"

**Comment by ksjdragon** [comment]
Wait, are you saying there is no y scrollbar currently?

**Comment by yamanq** [comment]
yes, y-scrollbars are the most common scrollbar

**Comment by ksjdragon** [comment]
It appears for me is the weird thing. I never disabled the y scrollbar

**Comment by yamanq** [comment]
screenshot?

**Comment by ksjdragon** [comment]
![image](https://cloud.githubusercontent.com/assets/8921294/14578194/7a28ecea-034f-11e6-8cb1-5f7884d989a3.png)

**Comment by ksjdragon** [comment]
Will do, i'll just style the scrollbar con css

**Comment by ksjdragon** [comment]
fixed in c4ee4675de4ca9e527cb299523390ebf864d215e

**Comment by yamanq** [comment]
![image](https://cloud.githubusercontent.com/assets/8166212/14587233/b9890576-047d-11e6-819b-190f8e155162.png)
can't scroll to see entire content

**Comment by yamanq** [comment]
![image](https://cloud.githubusercontent.com/assets/8166212/14592742/11adf820-04f0-11e6-8b5d-632313fc62c9.png)

**Comment by ksjdragon** [comment]
I think this is also fixed in bcafd576b1c2aa73e69c8d0fbecaf5e184e416cc but not sure, check on your side.

**Comment by yamanq** [comment]
![pic](https://cloud.githubusercontent.com/assets/8166212/14721449/6dd66f42-07d4-11e6-92e6-c8610776fb4b.png)

**Comment by ksjdragon** [comment]
this is a incompatibility issue with firefox, and there is no workaround around it that I have found. I think this is only affecting it visually, so it's not a problem.

**Comment by yamanq** [comment]
I don't think you understand. The issue is that the bottom of scroll-able area does not display all the information. I am almost sure that you added a 5% margin-bottom which fixed the issue, but maybe I am imagining things.

**Comment by ksjdragon** [comment]
I'll look again on firefox

**Comment by ksjdragon** [comment]
Does this still persist? I checked on various screen resolutions and on various browsers, and it seems fine to me.
